"""ADD EMAIL_ADDRESS AND NEXT_LOGIN_RESET FIELDS INTO USERS TABLE

Revision ID: 93b63a8c67c0
Revises: 6bfadd674628
Create Date: 2025-09-30 18:00:46.739796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b63a8c67c0'
down_revision: Union[str, Sequence[str], None] = '6bfadd674628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('next_login_reset', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'next_login_reset')
    op.drop_column('users', 'email_address')
    # ### end Alembic commands ###
